services:
  - type: web
    name: gateway-custom
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
